# 학습 체크리스트

- [x] Promise
- [x] Async

# 학습 내용

## 1️⃣ Promise

`**Promsie**` 프로미스는 객체이며, 비동기 작동의 결과와 그 값을 저장하고 있tㅡㅂ니다.

프로미스는 말 그대로 약속이라는 의미로, 특정 시점 미래에 값을 제공하는 목적으로 사용됩니다.

### 상태 State

- _pending_: initial state, neither fulfilled nor rejected.
- _fulfilled_: meaning that the operation was completed successfully.
- _rejected_: meaning that the operation failed.

We say that a promise is *`settled`* if it is not pending, i.e. if it is either fulfilled or rejected. Being settled is not a state, just a linguistic convenience.

### Fate

- resolved
- rejected

```jsx
new Promise((resolveOuter) => {
  resolveOuter(
    new Promise((resolveInner) => {
      setTimeout(resolveInner, 1000);
    })
  );
});
```

Promise(resolved) → resolve 인자로 또다른 프로미스 객체를 인자로 받는 함수를 넣었을 때

이는 1초동안의 Inner 부분이 실행되고 resolved되기 전까지 outer pormise는 fulfiled 라고 할 수 없습니다.

(It is resolved with another promise, and therefore won't be *fulfilled* until 1 second later, when the inner promise fulfills.)

### 예제

1️⃣

```jsx
// THE PROMISE VERSION
const fakeRequestPromise = (url) => {
  return new Promise((resolve, reject) => {
    const delay = Math.floor(Math.random() * 4500) + 500;
    setTimeout(() => {
      if (delay > 4000) {
        reject('Connection Timeout :(');
      } else {
        resolve(`Here is your fake data from ${url}`);
      }
    }, delay);
  });
};

fakeRequestPromise('zzz.com/api/coffee/page1')
  .then(() => {
    console.log('IT WORKED!!!!!! (page1)');
    fakeRequestPromise('zzz.com/api/coffee/page2')
      .then(() => {
        console.log('IT WORKED!!!!!! (page2)');
        fakeRequestPromise('zzz.com/api/coffee/page3')
          .then(() => {
            console.log('IT WORKED!!!!!! (page3)');
          })
          .catch(() => {
            console.log('OH NO, ERROR!!! (page3)');
          });
      })
      .catch(() => {
        console.log('OH NO, ERROR!!! (page2)');
      });
  })
  .catch(() => {
    console.log('OH NO, ERROR!!! (page1)');
  });
```

비동기 실행 → 비동기 실행 → 비동기 실행

프로미스를 사용해도 콜백지옥이 생긴다는 것을 알 수 있습니다.

이유는 promise 의 then실행문 안에 또 다른 프로미스 객체를 실행하여 로직을 구성했기 때문입니다.

하지만 이같은 문제는 promise chaining으로 해결 가능합니다.

```jsx
const fakeRequestPromise = (url) => {
  const delay = Math.floor(Math.random() * 4500) + 500;
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (delay > 4000) {
        reject('Connection Timeout :(');
      } else {
        resolve('Here is your Fake Data');
      }
    }, delay);
  });
};

fakeRequestPromise('books.com')
  .then((res) => {
    console.log('It worked!');
    console.log(res);
    return fakeRequestPromise('amazon.com');
  })
  .then((res) => {
    console.log('It worked, again');
    console.log(res);
    return fakeRequestPromise('apple.com');
  })
  .then((res) => {
    console.log('It worked, again');
    console.log(res);
  });
```

then 실행문에서 또다른 promise객체를 반환하는 함수 혹은 promise 객체를 실행하는 것이 아니라 promise객체를 반환하는 함수 혹은 promise 객체 를 return 해주고 then으로 체이닝할 수 있습니다.

추가로 하나의 then에서 promise 상태가 rejected로 settled된다면 catch 구문이 실행됩니다.

### 2️⃣

```jsx
const fakeRequest = (url) => {
  return new Promise((resolve, reject) => {
    const rand = Math.random();
    setTimeout(() => {
      if (rand < 0.1) {
        resolve(100)
      } else {
        reject(-100)
      }
    }, 1000)
  })
}

fakeRequest()
  .then((res) => {
    const resNum = res + 300;
    console.log(resNum);
	**//return resNum**
  })
  .catch((rej) => {
    const rejNum = rej - 100;
    console.log(rejNum);
  })
```

**`//return resNum`** : 이렇게 사용하고 해당 함수를 변수에 넣게 되면 그 변수는 resNum의 최종 값이 아닌, promise<pending> 값을 변수에 넣는 것입니다..

그리고 그 promise객체 언제 값이 들어올지 예측할 수 없습니다.

예를 들어…

```jsx
const fakeRequest = (url) => {
  return new Promise((resolve, reject) => {
    const rand = Math.random();
    setTimeout(() => {
      if (rand < 0.1) {
        resolve(100)
      } else {
        reject(-100)
      }
    }, 1000)
  })
}

**const num = fakeRequest()**
  .then((res) => {
    const resNum = res + 300;
    return resNum;
  })
  .catch((rej) => {
    const rejNum = rej - 100;
    return rejNum;
  })

**setTimeout(() => {
  console.log(num);
}, 10000); //Promise {400}**
```

### 3️⃣

```jsx
const delayedColorChange = (newColor, delay) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      document.body.style.backgroundColor = newColor;
      resolve();
    }, delay);
  });
};

delayedColorChange('red', 1000)
  .then(() => {
    return delayedColorChange('blue', 1000);
  })
  .then(() => {
    return delayedColorChange('green', 1000);
  })
  .then(() => {
    return delayedColorChange('yellow', 1000);
  });
```

🔗 참고자료

| 제목    | 링크                                                                                     |
| ------- | ---------------------------------------------------------------------------------------- |
| Promise | https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise |
| Fate    | https://github.com/domenic/promises-unwrapping/blob/master/docs/states-and-fates.md      |

## 2️⃣ Async Await

### async

Promise와 크게 다르지 않습니다. Syntax Sugar. 같은 기능이지만 코드를 더 간결하게 만들어줍니다.

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/e15a72ec-c875-430d-9f44-d4a0dce940b9/Untitled.png)

async 키워드를 사용한 함수를 호출하는 것만으로 함수의 return값이 없음에도 Promise객체가 반환된다는 것을 알 수 있습니다.

```jsx
const sing = async () => {
  return 'LaLaLa';
};

sing().then((res) => {
  console.log('Promise Fulfilled: ', res); //Promise Fulfilled:  LaLaLa
});
```

그러면 언제 rejected된다는 것일까? → sing 함수에서 에러가 나면 Promise<rejected> 객체를 반환합니다.

```jsx
const sing = async () => {
  throw new Error('Oooops');
  return 'LaLaLa';
};
sing().catch((err) => {
  console.log('boom!'); //boom!
});
```

Oooops는 실행되지 않습니다. 왜냐하면 catch를 통해 에러가 발생할 경우 실행할 구문을 따로 만들어줬기 때문에 에러가 발생하지 않습니다.

```jsx
const login = async (username, password) => {
  if (!username || !password) throw 'Missing Data';
  if (password === 'abcde') return 'WELCOME';
  throw 'Invalid Password!';
};

login('heymama', 'acde')
  .then((msg) => {
    console.log('login continuing...', msg);
  })
  .catch((err) => {
    console.log(err);
  });
```

### await

2-3 Promise 예제 코드였습니다. 이를 await로 변환해보겠습니다.

`before`

```jsx
const delayedColorChange = (newColor, delay) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      document.body.style.backgroundColor = newColor;
      resolve();
    }, delay);
  });
};

delayedColorChange('red', 1000)
  .then(() => delayedColorChange('blue', 1000))
  .then(() => delayedColorChange('green', 1000))
  .then(() => delayedColorChange('yellow', 1000));
```

`after`

```jsx
const delayedColorChange = (newColor, delay) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      document.body.style.backgroundColor = newColor;
      resolve();
    }, delay);
  });
};

// delayedColorChange("red", 1000)
//   .then(() => delayedColorChange("blue", 1000))
//   .then(() => delayedColorChange("green", 1000))
//   .then(() => delayedColorChange("yellow", 1000))

async function rainbow() {
  await delayedColorChange('red', 1000);
  await delayedColorChange('blue', 1000);
  await delayedColorChange('green', 1000);
  await delayedColorChange('yellow', 1000);
}

async function printRainbow() {
  await rainbow();
  console.log('End');
}

printRainbow();
```

## async await 에서 catch는…?

```jsx
const fakeRequestPromise = (url) => {
  return new Promise((resolve, reject) => {
    const delay = Math.floor(Math.random() * 4500) + 500;
    setTimeout(() => {
      if (delay > 2000) {
        reject('Connection Timeout :(');
      } else {
        resolve(`Here is your fake data from ${url}`);
      }
    }, delay);
  });
};

async function makeTwoRequests() {
  let data1 = await fakeRequestPromise('/page1');
  console.log('hello!'); //rejected 된 경우, error가 발생하여 hello를 출력하지 않는다.
}
```

### try - catch

```jsx
const fakeRequestPromise = (url) => {
  return new Promise((resolve, reject) => {
      const delay = Math.floor(Math.random() * (4500)) + 500;
      setTimeout(() => {
          if (delay > 4000) {
              reject('Connection Timeout :(')
          } else {
              resolve(`Here is your fake data from ${url}`)
          }
      }, 1000)
  })
}

async function makeTwoRequests() {
  try {
    let data1 = await fakeRequestPromise('/page1');
    **console.log(data1); //Here is your fake data from /page1 //type:string
    return data1**
  } catch (e) {
    console.log("hello!");
		console.log("Error:", e);
  }
}

const data = makeTwoRequests();
**console.log(data); //Promise {<pending>}**
```

🔗 참고자료

| 제목  | 링크                                                                                        |
| ----- | ------------------------------------------------------------------------------------------- |
| async | https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function |

# 회고

## 1️⃣ 배운 점

- 비동기가 무엇이며 왜 웹 개발에서 비동기가 중요한지 배웠습니다. 싱글스레드의 한계를 극복할 수 있다는 점과 논블락 형태로 코드가 비동기로 진행됨에 따라 어떻게 코드를 관리해야하는지 알 수 있었습니다. 비동기 처리는 동기를 비동기로 만드는 것이 아니라 비동기로 작동하는 코드를 어떻게 제어해줄 것인지의 문제인 것도 알게 되었습니다.
- async와 await에 대해 알 수 있었습니다. 또한 Promise의 thenable객체가 무엇인지, 예외처리는 어떻게 해야하는지 알았습니다.

## 2️⃣ 배울 점

- 비동기를 집중적으로 공부한 이유는 Console.readLine이 비동기로 작동하는 메소드이기 때문입니다. 오늘 배운 것처럼 해당 메소드의 콜백 내부에 많은 로직을 담게 되면 콜백지옥에 빠질 수 있다는 점과, promise객체를 반환하는 메소드를 만들면 다른 모듈에서 해당 메소드를 위임할 수 있다고 생각했기 때문입니다. 이를 토대로 구현을 시도해봐야겠습니다.
